apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    - name: user
      image: andryran/user:v1
      resources:
        limits:
          memory: "128Mi"
          cpu: "1"
        requests:
          cpu: "500m" 
          memory: "128Mi" 
      ports:
        - containerPort: 8080
            