apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    - name: user
      image: andryran/user:v1
      ports:
        - containerPort: 8080
            