apiVersion: networking.k8s.io/v1
kind: Ingress
  name: uservice-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /api/
            backend: 
              serviceName: user
              servicePort: 8080
